apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
data:
  datasources.yml: |
{{ .Files.Get "files/grafana/provisioning/datasources/datasources.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
data:
  dashboards.yml: |
{{ .Files.Get "files/grafana/provisioning/dashboards/dashboards.yml" | indent 4 }}
  payflow-overview.json: |
{{ .Files.Get "files/grafana/provisioning/dashboards/payflow-overview.json" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.observability.grafanaImage }}
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payflow-secrets
                  key: grafana-admin-password
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - port: 3000
      targetPort: 3000
