apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |
{{ .Files.Get "files/otel-collector-config.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.observability.otelCollectorImage }}
          args: ["--config=/etc/otel-collector-config.yaml"]
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 8889
          volumeMounts:
            - name: config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: otel-collector
spec:
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 8889
      targetPort: 8889
