apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
data:
  prometheus.yml: |
{{ .Files.Get "files/prometheus.yml" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.observability.prometheusImage }}
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090
      targetPort: 9090
