apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
data:
  tempo.yaml: |
{{ .Files.Get "files/tempo.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo
    spec:
      containers:
        - name: tempo
          image: {{ .Values.observability.tempoImage }}
          args: ["-config.file=/etc/tempo.yaml"]
          ports:
            - containerPort: 3200
            - containerPort: 4317
          volumeMounts:
            - name: config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
      volumes:
        - name: config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: tempo
spec:
  selector:
    app.kubernetes.io/name: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
