apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payflow-gateway
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
