apiVersion: v1
kind: Secret
metadata:
  name: payflow-secrets
  labels:
    {{- include "payflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  grafana-admin-password: {{ .Values.secrets.grafanaAdminPassword | quote }}
