<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Payflow.Notifications.Domain\Payflow.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Payflow.Shared.Kernel\Payflow.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\Payflow.Shared.Contracts\Payflow.Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
